# Generated by Django 5.1 on 2024-09-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BayHacks_backend', '0006_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='email_sent',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='cookies_over_time',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
