# Generated by Django 5.1 on 2024-09-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BayHacks_backend', '0007_remove_customusermodel_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiedata',
            name='status',
            field=models.CharField(choices=[('Danger', 'Danger'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=10),
        ),
    ]
