"use client"
import FullLayout from "../src/layouts/FullLayout";
import Head from "next/head";
import "../styles/style.scss";
import { SessionProvider } from 'next-auth/react';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>BayHacks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="csrf-token" content="{% csrf_token %}" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SessionProvider session={pageProps.session}>
        <FullLayout>
          <Component {...pageProps} />
        </FullLayout>
      </SessionProvider>
    </>
  );
}



export default MyApp;
