# Generated by Django 5.1 on 2024-08-31 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BayHacks_backend', '0002_cookiedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiedata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
