# Generated by Django 5.1 on 2024-09-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BayHacks_backend', '0004_customusermodel_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='companies_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='cookies_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='email_sent',
            field=models.IntegerField(default=0),
        ),
    ]
